// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMcfR_rrgPnjFUxwkmLYuCaKdpYZ_XKvI',
    appId: '1:1061812926990:web:eef629366631b85d505a5f',
    messagingSenderId: '1061812926990',
    projectId: 'pharmcare-575e7',
    authDomain: 'pharmcare-575e7.firebaseapp.com',
    storageBucket: 'pharmcare-575e7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDROwZ8ZuhcQKAIrm-Z2CH4R0Zo25pOSaU',
    appId: '1:1061812926990:android:306f8ede38c31130505a5f',
    messagingSenderId: '1061812926990',
    projectId: 'pharmcare-575e7',
    storageBucket: 'pharmcare-575e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjChEn1NcUUFc-_LdfRG37U4FaISBGFLE',
    appId: '1:1061812926990:ios:de853e8f0f88a66b505a5f',
    messagingSenderId: '1061812926990',
    projectId: 'pharmcare-575e7',
    storageBucket: 'pharmcare-575e7.firebasestorage.app',
    iosBundleId: 'com.example.pharmcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjChEn1NcUUFc-_LdfRG37U4FaISBGFLE',
    appId: '1:1061812926990:ios:de853e8f0f88a66b505a5f',
    messagingSenderId: '1061812926990',
    projectId: 'pharmcare-575e7',
    storageBucket: 'pharmcare-575e7.firebasestorage.app',
    iosBundleId: 'com.example.pharmcare',
  );
}
